services:
  - type: web
    name: relationship-calculator-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: relationship-calculator-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: CORS_ORIGINS
        value: https://relationship-calculator-web.onrender.com
      - key: RATE_LIMIT_PER_MINUTE
        value: 60
      - key: LOG_LEVEL
        value: INFO 