"""Add generacion field to Relationship model

Revision ID: aa715ee9a01e
Revises: 
Create Date: 2025-04-17 16:58:18.862521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'aa715ee9a01e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable
    op.add_column('relationships', sa.Column('generacion', sa.Integer(), nullable=True))
    
    # 2. Update existing rows with default values based on relationship code
    conn = op.get_bind()
    conn.execute(text("""
        UPDATE relationships
        SET generacion = CASE code
            WHEN 'FS' THEN 1
            WHEN 'HS' THEN 1
            WHEN 'GP' THEN 2
            WHEN 'AU' THEN 2
            WHEN '1C' THEN 2
            WHEN 'H1C' THEN 2
            WHEN 'GAU' THEN 3
            WHEN '1C1R' THEN 3
            WHEN '2C' THEN 3
            WHEN '2C1R' THEN 3
            WHEN 'H2C' THEN 3
            WHEN 'GGAU' THEN 4
            WHEN '1C2R' THEN 4
            WHEN '3C' THEN 4
            WHEN '4C' THEN 5
            WHEN '5C' THEN 6
            WHEN '6C' THEN 7
            WHEN '7C' THEN 8
            WHEN '8C+' THEN 9
            ELSE 0
        END
    """))
    
    # 3. Make column not nullable
    op.alter_column('relationships', 'generacion',
               existing_type=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'generacion')
    # ### end Alembic commands ###
